### PR TITLE
Improve equipment grid mod compatibility

### PR DESCRIPTION
**Pull request by ryepup**
Applied [suggestion from Glendening](https://mods.factorio.com/mod/SpidertronEngineer/discussion/5f81aaa86c91db28401e0848) to add more categories to the equipment grid and allow more modded vehicle parts to work inside spidertron.

I tested with Krastorio2.

### CODE REVIEW

**Comment by tburrows13** [comment]
Thanks for this. Let me know if you're done and I'll merge and release. Can you confirm that it still works with non-vehicle armour? I see that you've removed the `"armor", "spidertron", "vehicle", "armoured-vehicle"` categories, but I don't remember much about it from when I added that bit.

**Comment by ryepup** [comment]
I didn't check that, lemme revert everything I didn't directly test

**Comment by ryepup** [comment]
OK, updated with only the changes I tested, without some of the other code from the mod forum.

**Comment by tburrows13** [comment]
Nice, thanks for your help!

**Comment by ryepup** [comment]
Thanks for the great mod!

**Pull request merged**
